# Generated by Django 5.0.1 on 2025-11-16 10:57

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_service', '0001_initial'),
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_price_per_hour', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Base Price per Hour (UAH)')),
                ('deposit_percentage', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Deposit Percentage')),
                ('opening_time', models.TimeField(default='09:00', verbose_name='Opening Time')),
                ('closing_time', models.TimeField(default='21:00', verbose_name='Closing Time')),
                ('min_booking_hours', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum Booking Hours')),
                ('max_booking_hours', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Booking Hours')),
                ('advance_booking_days', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Advance Booking Days')),
                ('is_booking_enabled', models.BooleanField(default=True, verbose_name='Booking Enabled')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='Maintenance Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking Settings',
                'verbose_name_plural': 'Booking Settings',
            },
        ),
        migrations.CreateModel(
            name='StudioBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('booking_date', models.DateField(verbose_name='Booking Date')),
                ('booking_time', models.TimeField(verbose_name='Booking Time')),
                ('duration_hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration (hours)')),
                ('base_price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Base Price per Hour (UAH)')),
                ('services_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Services Total (UAH)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Total Amount (UAH)')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Deposit Amount (UAH)')),
                ('deposit_percentage', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Deposit Percentage')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending_payment', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_services', models.ManyToManyField(blank=True, related_name='bookings', to='studios.additionalservice', verbose_name='Additional Services')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='studios.location', verbose_name='Studio Location')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='payment_service.studiopayment', verbose_name='Payment')),
            ],
            options={
                'verbose_name': 'Studio Booking',
                'verbose_name_plural': 'Studio Bookings',
                'ordering': ['-booking_date', '-booking_time'],
                'indexes': [models.Index(fields=['booking_date', 'booking_time'], name='bookings_st_booking_e83be8_idx'), models.Index(fields=['status'], name='bookings_st_status_018e1f_idx'), models.Index(fields=['phone_number'], name='bookings_st_phone_n_131cee_idx'), models.Index(fields=['location'], name='bookings_st_locatio_ecce1f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='studiobooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending_payment', 'paid', 'confirmed'])), fields=('location', 'booking_date', 'booking_time'), name='unique_active_booking_location_datetime'),
        ),
    ]
