# Generated by Django 5.0.1 on 2025-11-16 10:57

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prop Category',
                'verbose_name_plural': 'Prop Categories',
                'db_table': 'prop_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropRentalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_items_per_booking', models.PositiveIntegerField(default=20, help_text='Maximum number of prop items per booking', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_rental_enabled', models.BooleanField(default=True, help_text='Enable/disable prop rental feature')),
                ('rental_terms', models.TextField(blank=True, help_text='Terms and conditions for prop rental')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prop Rental Settings',
                'verbose_name_plural': 'Prop Rental Settings',
                'db_table': 'prop_rental_settings',
            },
        ),
        migrations.CreateModel(
            name='PropItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Rental price in UAH', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Total quantity available', validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True, help_text='Internal notes for admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='props.propcategory')),
            ],
            options={
                'verbose_name': 'Prop Item',
                'verbose_name_plural': 'Prop Items',
                'db_table': 'prop_items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='prop_images/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prop_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='props.propitem')),
            ],
            options={
                'verbose_name': 'Prop Image',
                'verbose_name_plural': 'Prop Images',
                'db_table': 'prop_images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingPropItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_at_booking', models.DecimalField(decimal_places=2, help_text='Price of item at time of booking', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_items', to='bookings.studiobooking')),
                ('prop_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='props.propitem')),
            ],
            options={
                'verbose_name': 'Booking Prop Item',
                'verbose_name_plural': 'Booking Prop Items',
                'db_table': 'booking_prop_items',
            },
        ),
        migrations.AddIndex(
            model_name='propitem',
            index=models.Index(fields=['is_active', 'is_available'], name='prop_items_is_acti_1d0e71_idx'),
        ),
        migrations.AddIndex(
            model_name='propitem',
            index=models.Index(fields=['category', 'is_active'], name='prop_items_categor_a4e095_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingpropitem',
            unique_together={('booking', 'prop_item')},
        ),
    ]
