# Generated by Django 5.0.1 on 2025-11-16 10:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudioPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сума до сплати в UAH', max_digits=10)),
                ('description', models.CharField(default='Передоплата за оренду студії', max_length=255)),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liqpay_status', models.CharField(blank=True, help_text="Статус від LiqPay (напр. 'success', 'sandbox')", max_length=50, null=True)),
                ('checkbox_receipt_id', models.CharField(blank=True, help_text='ID чека в системі Checkbox', max_length=255, null=True)),
                ('checkbox_fiscal_code', models.CharField(blank=True, help_text='Фіскальний номер чека', max_length=255, null=True)),
                ('checkbox_status', models.CharField(blank=True, help_text="Статус чека в Checkbox (напр. 'DONE')", max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Платіж за студію',
                'verbose_name_plural': 'Платежі за студію',
            },
        ),
    ]
