# Generated by Django 5.0.1 on 2025-11-16 10:57

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clothing Category',
                'verbose_name_plural': 'Clothing Categories',
                'db_table': 'clothing_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingRentalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_items_per_booking', models.PositiveIntegerField(default=10, help_text='Maximum number of clothing items per booking', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('is_rental_enabled', models.BooleanField(default=True, help_text='Enable/disable clothing rental feature')),
                ('rental_terms', models.TextField(blank=True, help_text='Terms and conditions for clothing rental')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clothing Rental Settings',
                'verbose_name_plural': 'Clothing Rental Settings',
                'db_table': 'clothing_rental_settings',
            },
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large'), ('XXXL', '3X Large'), ('ONE_SIZE', 'One Size')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Rental price in UAH', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Total quantity available', validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True, help_text='Internal notes for admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='clothing.clothingcategory')),
            ],
            options={
                'verbose_name': 'Clothing Item',
                'verbose_name_plural': 'Clothing Items',
                'db_table': 'clothing_items',
                'ordering': ['category', 'name', 'size'],
            },
        ),
        migrations.CreateModel(
            name='ClothingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='clothing_images/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clothing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clothing.clothingitem')),
            ],
            options={
                'verbose_name': 'Clothing Image',
                'verbose_name_plural': 'Clothing Images',
                'db_table': 'clothing_images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingClothingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_at_booking', models.DecimalField(decimal_places=2, help_text='Price of item at time of booking', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to='bookings.studiobooking')),
                ('clothing_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='clothing.clothingitem')),
            ],
            options={
                'verbose_name': 'Booking Clothing Item',
                'verbose_name_plural': 'Booking Clothing Items',
                'db_table': 'booking_clothing_items',
            },
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['is_active', 'is_available'], name='clothing_it_is_acti_93fb85_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['category', 'is_active'], name='clothing_it_categor_c4b078_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingclothingitem',
            unique_together={('booking', 'clothing_item')},
        ),
    ]
