# Generated by Django 5.0.1 on 2025-11-16 10:57

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_id', models.CharField(choices=[('clothing', 'Professional Clothing Rental'), ('makeup', 'Makeup Services'), ('hair', 'Hair Styling Services'), ('equipment', 'Equipment Rental'), ('editing', 'Photo Editing Services'), ('other', 'Other Services')], max_length=50, unique=True, verbose_name='Service Type')),
                ('name', models.CharField(max_length=200, verbose_name='Service Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price (UAH)')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Estimated duration in minutes (0 if not applicable)', verbose_name='Duration (minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Additional Service',
                'verbose_name_plural': 'Additional Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Studio Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Hourly Rate (UAH)')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Image URL')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('capacity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Capacity (people)')),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated list of amenities', verbose_name='Amenities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Studio Location',
                'verbose_name_plural': 'Studio Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudioImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500, verbose_name='Image URL')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='studios.location', verbose_name='Studio Location')),
            ],
            options={
                'verbose_name': 'Studio Image',
                'verbose_name_plural': 'Studio Images',
                'ordering': ['location', 'order', 'created_at'],
            },
        ),
    ]
